### ISSUE TITLE
Can't connect to the web interface - 400: Bad Request

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/homeassistant_ynh#181]
### Describe the bug

*From a fresh install, I can't connect to the app, I get an error 400: Bad Request.*
*Exactly, the log says: `[homeassistant.components.http.forwarded] A request from a reverse proxy was received from 127.0.0.1, but your HTTP integration is not set-up for reverse proxies`

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 11.0.11
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

- *Install the app*
- *Try to reach it...*

### Logs

```
ERROR (MainThread) [homeassistant.components.http.forwarded] A request from a reverse proxy was received from 127.0.0.1, but your HTTP integration is not set-up for reverse proxies
```

**Comment by ewilly** [comment]
Strange first time it occurs...
Can you check in your `/home/yunohost.app/homeassistant/configuration.yaml` if it contain in the http section / trusted_proxies the line : 
`  use_x_forwarded_for: True`
`  trusted_proxies:`
`    - 127.0.0.1`
`    - ::1` 
 ?

**Comment by maniackcrudelis** [comment]
Yes of course !
I was about to try on a virtual machine and forgot that part, quite obvious ! Sorry

```
homeassistant:
  name: My home
  latitude: **.*****
  longitude: *.*****
  elevation: ***
  unit_system: metric
  currency: Euro
  country: FR
  time_zone: "Europe/Paris"
  external_url: "https://homeassistant.domain.tld"
  auth_providers:
   - type: command_line
     command: /home/yunohost.app/homeassistant/bin/ynh_ldap-auth.sh
     meta: true

http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

recorder:
  db_url: mysql://homeassistant:***@127.0.0.1/homeassistant?unix_socket=/var/run/mysqld/mysqld.sock&charset=utf8mb4
    
# Apply default set of integrations
default_config:

# Linked yaml files
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Switches
switch:
  - platform: command_line
    switches:   
      upgrade_homeassistant:
        command_on: "nohup bash -c /home/yunohost.app/homeassistant/bin/upgrade_homeassistant.sh $1 > /dev/null  2>&1 &"
        friendly_name: Upgrade Home Assistant
```

```
# see https://github.com/home-assistant/addons/blob/master/nginx_proxy/data/nginx.conf

location / {
        proxy_pass http://127.0.0.1:8123;
        proxy_set_header Host $host;
        proxy_redirect http:// https://;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        # Include SSOWAT user panel.
        include conf.d/yunohost_panel.conf.inc;
}
```
